version: '3'

volumes:
  db_data:
    driver: local


services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - db_data:/data/db
    ports:
      - 27017:27017
    environment:
      MONOGO_INITDB_DATABASE: yealink-provision
      